{
    "cchat" [
      {
        "id": 1,
        "title": "Sơ mi basic dáng suông",
        "type": "ÁO SƠ MI",
        "price-sale": "",
        "price":290000,
        "img": "/do-an-web-tinh/images/product/Ao-So-Mi.images/image1.jpeg",
        "img-hover":"/do-an-web-tinh/images/product/Ao-So-Mi.images/image1.1.jpeg",
      },
      {
        "id": 2,
        "title": "Sơ mi tay xoắn",
        "type": "ÁO SƠ MI",
        "price-sale": 249000,
        "price":320000,
        "img": "/do-an-web-tinh/images/product/Ao-So-Mi.images/image2.jpeg",
        "img-hover":"/do-an-web-tinh/images/product/Ao-So-Mi.images/image2.1.jpeg",
      },
      {
        "id": 3,
        "title": "Sơ mi basic vai rơi HT",
        "type": "ÁO SƠ MI",
        "price-sale": 249000,
        "price":360000,
        "img": "/do-an-web-tinh/images/product/Ao-So-Mi.images/image3.jpeg",
        "img-hover":"/do-an-web-tinh/images/product/Ao-So-Mi.images/image3.1.jpeg",
      },
      {
        "id": 4,
        "title": "Sơ mi suông tay thép 2023",
        "type": "ÁO SƠ MI",
        "price-sale": 269000,
        "price":710000,
        "img": "/do-an-web-tinh/images/product/Ao-So-Mi.images/image4.jpeg",
        "img-hover":"/do-an-web-tinh/images/product/Ao-So-Mi.images/image4.1.jpeg",
      },
      {
        "id": 5,
        "title": "Sơ mi tay phổng dài",
        "type": "ÁO SƠ MI KIỂU",
        "price-sale": 249000,
        "price":310000,
        "img": "/do-an-web-tinh/images/product/Ao-So-Mi-kieu.image/image1.jpeg",
        "img-hover":"/do-an-web-tinh/images/product/Ao-So-Mi-kieu.image/image1.1.jpeg",
      },
      {
        "id": 6,
        "title": "Sơ mi croptop phối cổ",
        "type": "ÁO SƠ MI KIỂU",
        "price-sale": 249000,
        "price":310000,
        "img": "/do-an-web-tinh/images/product/Ao-So-Mi-kieu.image/image2.jpeg",
        "img-hover":"/do-an-web-tinh/images/product/Ao-So-Mi-kieu.image/image2.1.jpeg",
      },
      { "id": 7,
      "title": "Sơ mi đá Ruby Jane",
      "type": "ÁO SƠ MI KIỂU",
      "price-sale": 349000,
      "price":419000,
      "img": "/do-an-web-tinh/images/product/Ao-So-Mi-kieu.image/image3.jpeg",
      "img-hover":"/do-an-web-tinh/images/product/Ao-So-Mi-kieu.image/image3.1.jpeg",
      },
      {
        "id": 8,
        "title": "Sơ mikiểu princess",
        "type": "ÁO SƠ MI KIỂU",
        "price-sale": 249000,
        "price":310000,
        "img": "/do-an-web-tinh/images/product/Ao-So-Mi-kieu.image/image4.jpeg",
        "img-hover":"/do-an-web-tinh/images/product/Ao-So-Mi-kieu.image/image4.1.jpeg",
      },
      {
        "id": 9,
        "title": "Áo thun cổ leo basic",
        "type": "ÁO THUN",
        "price-sale": 159000,
        "price":209000,
        "img": "/do-an-web-tinh/images/product/Ao-thun.image/image1.jpeg",
        "img-hover":"/do-an-web-tinh/images/product/Ao-thun.image/image1.1.jpeg",
      },
      {
        "id": 10,
        "title": "Áo thun ren ôm",
        "type": "ÁO THUN",
        "price-sale": 179000,
        "price":240000,
        "img": "/do-an-web-tinh/images/product/Ao-thun.image/image4.jpeg",
        "img-hover":"/do-an-web-tinh/images/product/Ao-thun.image/image4.1.jpeg",
      },
      {
        "id": 11,
        "title": "Áo thun bổ lưng sau",
        "type": "ÁO THUN",
        "price-sale": 399000,
        "price":169000,
        "img": "/do-an-web-tinh/images/product/Ao-thun.image/image2.jpeg",
        "img-hover":"/do-an-web-tinh/images/product/Ao-thun.image/image2.1.jpeg",
      },
      {
        "id": 12,
        "title": "Áo thun cổ leo tay cộc",
        "type": "ÁO THUN",
        "price-sale": 119000,
        "price":139000,
        "img": "/do-an-web-tinh/images/product/Ao-thun.image/image3.jpeg",
        "img-hover":"/do-an-web-tinh/images/product/Ao-thun.image/image3.1.jpeg",
      },
      {
        "id": 13,
        "title": "Khoác phối da kiểu sporty",
        "type": "ÁO KHOÁC",
        "price-sale": 499000,
        "price":609000,
        "img": "/do-an-web-tinh/images/product/Ao-khoac.image/image2.jpeg",
        "img-hover":"/do-an-web-tinh/images/product/Ao-khoac.image/image2.1.jpeg",
      },
      {
        "id": 14,
        "title": "Áo khoác HT ngắn",
        "type": "ÁO KHOÁC",
        "price-sale": 499000,
        "price":600000,
        "img": "/do-an-web-tinh/images/product/Ao-khoac.image/image1.jpeg",
        "img-hover":"/do-an-web-tinh/images/product/Ao-khoac.image/image1.1.jpeg",
      },
      {
        "id": 15,
        "title": "Măng tô tay phổng",
        "type": "ÁO MĂNG TÔ",
        "price-sale": 799000,
        "price":1029000,
        "img": "/do-an-web-tinh/images/product/Ao-Mang-To.image/image1.jpeg",
        "img-hover":"/do-an-web-tinh/images/product/Ao-Mang-To.image/image1.1.jpeg",
      },
      {
        "id": 16,
        "title": "Măng tô lá cổ tp tay zaclang",
        "type": "ÁO MĂNG TÔ",
        "price-sale": 349000,
        "price":1029000,
        "img": "/do-an-web-tinh/images/product/Ao-Mang-To.image/image2.jpeg",
        "img-hover":"/do-an-web-tinh/images/product/Ao-Mang-To.image/image2.1.jpeg",
      },
      {
        "id": 17,
        "title": "Set áo phối tay CV",
        "type": "",
        "price-sale": 799000,
        "price":1029000,
        "img": "/do-an-web-tinh/images/option1.imges/option1-img1.jpeg",
        "img-hover":"/do-an-web-tinh/images/option1.imges/option1--img1.jpeg",
      },
      {
        "id": 18,
        "title": "Măng tô tay bổng",
        "type": "",
        "price-sale": 699000,
        "price":910000,
        "img": "/do-an-web-tinh/images/option1.imges/option1-img2.jpeg",
        "img-hover":"/do-an-web-tinh/images/option1.imges/option1--img2.jpeg"
      },
      {
        "id": 19,
        "title": "Blazer dáng ngắn cổ tròn",
        "type": "",
        "price-sale": 469000,
        "price":689000,
        "img": "/do-an-web-tinh/images/option1.imges/option1-img3.jpeg",
        "img-hover":"/do-an-web-tinh/images/option1.imges/option1--img3.jpeg"
      },
      {
        "id": 20,
        "title": "Set Blazer răng sói",
        "type": "",
        "price-sale": 599000,
        "price":889000,
        "img": "/do-an-web-tinh/images/option1.imges/option1-img4.jpeg",
        "img-hover":"/do-an-web-tinh/images/option1.imges/option1--img4.jpeg"
      },
      {
        "id": 21,
        "title": "Sơ mi cổ trụ gấu vát",
        "type": "",
        "price-sale": 249000,
        "price":270000,
        "img": "/do-an-web-tinh/images/option1.imges/option1-img5.jpeg",
        "img-hover":"/do-an-web-tinh/images/option1.imges/option1--img5.jpeg"
      },
      {
        "id": 22,
        "title": "Set Blazer cổ tròn",
        "type": "",
        "price-sale": 549000,
        "price":789000,
        "img": "/do-an-web-tinh/images/option1.imges/option1-img6.jpeg",
        "img-hover":"/do-an-web-tinh/images/option1.imges/option1--img6.jpeg"
      },
      {
        "id": 23,
        "title": "Áo khoác HT ngăn",
        "type": "",
        "price-sale": 499000,
        "price":600000,
        "img": "/do-an-web-tinh/images/option1.imges/option1-img7.jpeg",
        "img-hover":"/do-an-web-tinh/images/option1.imges/option1--img7.jpeg"
      },
      {
        "id": 24,
        "title": "Blazer tweed 2 CV",
        "type": "",
        "price-sale": 579000,
        "price":799000,
        "img": "/do-an-web-tinh/images/option1.imges/option1-img8.jpeg",
        "img-hover":"/do-an-web-tinh/images/option1.imges/option1--img8.jpeg"
      },
    {
      "id": 25,
      "title": "Sét Blazer tay dài CV",
      "type": "",
      "price-sale": 699000,
      "price":1049000,
      "img": "/do-an-web-tinh/images/option1.imges/option1-img9.jpeg",
      "img-hover":"/do-an-web-tinh/images/option1.imges/option1--img9.jpeg"
    }
    ]
  }